# v3.11.0 candidate
# https://github.com/TACC/Core-CMS/pull/638
FROM taccwma/core-cms:c35486d

WORKDIR /code

COPY /src/apps /code/apps
COPY /src/taccsite_custom /code/taccsite_custom
COPY /src/taccsite_cms /code/taccsite_cms
