# TACC/Core-CMS#792 (v4.7.0 candidate)
FROM taccwma/core-cms:_______

WORKDIR /code

COPY /src/apps /code/apps
COPY /src/taccsite_custom /code/taccsite_custom
COPY /src/taccsite_cms /code/taccsite_cms
