# TACC/Core-CMS#675 (v3.12.0 candidate)
FROM taccwma/core-cms:6bb3f59

WORKDIR /code

COPY /src/apps /code/apps
COPY /src/taccsite_custom /code/taccsite_custom
COPY /src/taccsite_cms /code/taccsite_cms
