def _set_extension(reg, reg_ents, reg_conts):
    org_types = {
            'carrier': 'Insurance Carrier',
            'tpa_aso': 'Plan Administrator¹ (TPA/ASO)',
            'pbm': 'Pharmacy Benefit Manager (PBM)'
    }
    return {
            'biz_name': reg[5],
            'type': org_types[reg[4]] if (reg[4] and reg[4] in org_types.keys()) else None,
            'location': '{city}, {state}'.format
                (
                    city=reg[7],
                    state=reg[8]
                ),
            'reg_status': reg[3].title(),
            'reg_id': reg[0],
            'year': reg[10],
            'view_modal_content': _set_modal_content(reg, org_types)
        }

def _set_modal_content(reg, org_types):
    return {
        'biz_name': reg[5],
        'type': org_types[reg[4]] if (reg[4] and reg[4] in org_types.keys()) else None,
        'city': reg[7],
        'state': reg[8],
        'address': reg[6],
        'zip': reg[9],
        'for_self': reg[2],
        'year': reg[10],
        'org_types': org_types,
        'us_state_list': [
            'AL - Alabama',
            'AK - Alaska',
            'AS - American Samoa',
            'AR - Arkansas',
            'AZ - Arizona',
            'CA - California',
            'CO - Colorado',
            'CT - Connecticut',
            'DE - Delaware',
            'DC - District of Columbia',
            'FL - Florida',
            'GA - Georgia',
            'GU - Guam',
            'HI - Hawaii',
            'ID - Idaho',
            'IL - Illinois',
            'IN - Indiana',
            'IA - Iowa',
            'KS - Kansas',
            'KY - Kentucky',
            'LA - Louisiana',
            'ME - Maine',
            'MD - Maryland',
            'MA - Massachusetts',
            'MI - Michigan',
            'MN - Minnesota',
            'MS - Mississippi',
            'MO - Missouri',
            'MT - Montana',
            'NE - Nebraska',
            'NH - New Hampshire',
            'NJ - New Jersey',
            'NM - New Mexico',
            'NV - Nevada',
            'NY - New York',
            'NC - North Carolina',
            'ND - North Dakota',
            'MP - Northern Mariana Islands',
            'OH - Ohio',
            'OK - Oklahoma',
            'OR - Oregon',
            'PA - Pennsylvania',
            'RI - Rhode Island',
            'SC - South Carolina',
            'SD - South Dakota',
            'TN - Tennessee',
            'TX - Texas',
            'UT - Utah',
            'VT - Vermont',
            'VA - Virginia',
            'VI - Virgin Islands',
            'WA - Washington',
            'WV - West Virginia',
            'WI - Wisconsin',
            'WY - Wyoming'
        ],
    }
