version: "3"
services:
  cms:
    build: .
    ports:
      - 8000:8000
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    container_name: style_cms
    hostname: style_cms
    volumes:
      - ./src/apps:/code/apps
      - ./src/taccsite_custom:/code/taccsite_custom
      - ./src/taccsite_cms/custom_app_settings.py:/code/taccsite_cms/custom_app_settings.py
      - ./src/taccsite_cms/urls_custom.py:/code/taccsite_cms/urls_custom.py
      - ./src/taccsite_cms/settings_custom.py:/code/taccsite_cms/settings_custom.py
      - ./src/taccsite_cms/settings_local.py:/code/taccsite_cms/settings_local.py
      - ./src/taccsite_cms/secrets.py:/code/taccsite_cms/secrets.py
      # IMPORTANT: The container is overwritten by host directory created by Docker because no host directory existed
      # SEE: https://stackoverflow.com/questions/66724297/docker-compose-volume-copying-folder-from-docker-container-to-host-when-executi
      # IDEA: (Me) Create symlinks in the container (via the Dockerfile) and work with those paths even though you can not see them locally
      # IDEA: (StackOverflow) https://stackoverflow.com/questions/66724297/docker-compose-volume-copying-folder-from-docker-container-to-host-when-executi#comment117993119_66734699
    networks:
      - style_cms_net

  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=taccforever
      - POSTGRES_USER=postgresadmin
      - POSTGRES_DB=taccsite
      - PGDATA=/var/lib/postgresql/data/taccsite
    volumes:
      - style_cms_postgres_data:/var/lib/postgresql/data
    hostname: style_cms_postgres
    container_name: style_cms_postgres
    networks:
      - style_cms_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ulimits:
      memlock: -1
    environment:
      - ES_HEAP_SIZE:1g
      - discovery.type=single-node
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - style_cms_es_data:/usr/share/elasticsearch/data
    container_name: style_cms_elasticsearch
    ports:
      - 9201:9200
    networks:
      - style_cms_net

volumes:
  style_cms_postgres_data:
  style_cms_es_data:

networks:
  style_cms_net:
