# TACC/Core-CMS#926 (unreleased v4.26.N)
FROM taccwma/core-cms:fix-core-styles-v0-header-bugs

WORKDIR /code

COPY /src/taccsite_custom /code/taccsite_custom
COPY /src/taccsite_cms /code/taccsite_cms
