name: Example CMS Builds
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'example_cms/**'

jobs:
  build_commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example_cms
    steps:
      - uses: actions/checkout@v2
      - name: Get shortsha
        id: vars
        run: |
          if [ -z "$EVENT_SHA" ]; then SHORT_SHA=${GITHUB_SHA::8}; else SHORT_SHA=${EVENT_SHA::8}; fi
          echo ::set-output name=sha_short::${SHORT_SHA}
        env:
          EVENT_SHA: ${{ github.event.client_payload.sha }} 
      - name: Print shortsha
        run: |
          echo $SHORTSHA
        env: 
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}
      - uses: docker/setup-buildx-action@v2
        name: Setup Docker Builds
      - uses: docker/login-action@v2
        name: Log in to docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        name: Build & push commit tagged Docker image
        with:
          context: example_cms
          push: true
          tags: taccwma/example-cms:${{ steps.vars.outputs.sha_short }}